### PR TITLE
[F] Implement navigation menu

### PR DESCRIPTION
**Pull request by John4850**
Initial component is created

### CODE REVIEW

**Comment by John4850** [comment]
CSS is in need of review,
Problem:
 -Small screens and mobile devices the link layout gets distorted.
Suggested Fix:
-Downsize the buttons,
-Create an App or Navigation wrapper
-Ask someone better at CSS for suggestions.

**Comment by John4850** [comment]
Navigation persists across pages, as well as footer.

Screen Shot 2023-05-27 at 2 17 00 PM
Screen Shot 2023-05-27 at 2 17 04 PM
Screen Shot 2023-05-27 at 2 17 10 PM

**Review by John4850 — COMMENTED** [review]
Much cleaner

**Comment by MollyJeanB** [comment]
Made some styles adjustments and extracted the Layout into a separate component.

Screenshot 2023-05-27 at 8 08 01 PM

**Review by MollyJeanB — APPROVED** [review]
Great work getting this started @John4850 👏 👏 👏

**Pull request merged**
